env:
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug
sudo: false
cache:
  apt: true
  directories:
    - programs
notifications:
  email: false

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - build-essential
      - libblas-dev
      - liblapack-dev
      - libboost-dev
      - clang-3.6
      - gfortran
      - doxygen
      - graphviz

language: cpp
compiler: clang

before_install:
  - ./scripts/setup_astyle.sh
  - export PATH=$PWD/programs/astyle/build/gcc/bin:$PATH
  - ./scripts/check_indentation.sh

install:
  - export PRG=$PWD/programs
  - export CASA=$PWD
  - export CXX=clang++-3.6
  - export PATH=$PWD/programs/cmake/bin:$PATH
  - export PATH=$PWD/programs/ninja:$PATH
  - export TRILINOS_DIR=$PWD/programs/trilinos
  - export DEAL_II_DIR=$PWD/programs/dealii
  - export SUNDIALS_DIR=$PWD/programs/sundials
  - export PATH=$PWD/programs/astyle/build/gcc/bin:$PATH
  - export PATH=$PRG/numdiff/bin:$PATH
  - ./scripts/set_cache.sh
  - mkdir build
  - cd build
  - cmake -GNinja -DCMAKE_INSTALL_PREFIX=/home/travis/deal2lkit-$BUILD_TYPE -DD2K_ENABLE_TESTING=ON -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
  - ninja -j4 install
  - tar cvfz /home/travis/deal2lkit-CI-$BUILD_TYPE.tgz /home/travis/deal2lkit-$BUILD_TYPE
  - tar cvfz /home/travis/dealii-CI-environment.tgz $PWD/programs
  
script:
  - ctest -j4 -V -R "${BUILD_TYPE,,}"
    
deploy:
  provider: releases
  api_key:
    secure: JBIOZ2GRmxWduUKtM6E623y4lju4P7nKsa+DYh2qwrlSqQDrDoRPwGt9LW8T8l9CiMhvKbXTdzEsmQMdtHGzRW2GV9VU/lsugMTEGJMtjd/ly0dwTyscBhnBudLnk/z1lZB/wKgxi2r+fmsthRctvtzkIK8uRBqA0ivkAD9wFRU=
  file:
    - /home/travis/deal2lkit-CI-$BUILD_TYPE.tgz
    - /home/travis/dealii-CI-environment.tgz
  skip_cleanup: true
  on:
    repo: mathlab/deal2lkit
    tags: true
    all_branches: true
